# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d84e689acac1358b1951acfa331960b47a1825207f058b9b7d78f549520a217d54a7f739fdf9593baed5b7e27c4276e8e842958c5dfeff43ccae6777225fcbc1

test:
  secret_key_base: 43465afdf8952bb4e008a70386b9b848b3d4e5c444563bdde1ccc9d1b02cdf4c72e32b8384567b90eeeda4de4907789ef29c63d5f3b1f0afe4311bbdca9d6c7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
